#include <stdio.h>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int fibonacci(int);

int main() {
	int index = 1;
	int fValue = 0;
	long long sum = 0;
	while (1) {
		fValue = fibonacci(index);
		if (fValue > 4000000) break;

		if (fValue % 2 == 0) {
			sum += fValue;
		}

		index++;
	}

	printf("%d", sum);
	return 0;
}

int fibonacci(int value) {
	int first = 1, second = 2, start = 3, temp = 0;
	if (value <= 0) 
		return 0;
	if (value == first)
		return first;
	if (value == second)
		return second;

	while (value >= start) {
		temp = first + second;
		first = second;
		second = temp;
		start++;
	}

	return temp;
}